name: publish-beta
on:
  push:
    branches: [beta]
  workflow_dispatch:
jobs:
  publish-beta:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set Node.js from .nvmrc
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Install Dependencies
        run: pnpm install

      - name: Build Beta
        run: pnpm run build:beta

      - name: Publish Chrome
        run: pnpm run publish:chrome
        env:
          CHROME_EXTENSION_ID: mkgdgjnaaejddflnldinkilabeglghlo
          CHROME_CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
          CHROME_CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
          CHROME_REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
